### ISSUE TITLE
Cannot Upgrade To Any Version

### ISSUE THREAD

**Issue by atom0s** [felixrieseberg/npm-windows-upgrade#50] opened 2015-12-11 05:46 UTC
Anytime I try to upgrade, the script fails with the following screen:
http://i.imgur.com/bT3eLxp.png

The 'Here is the error:' block is always empty so I am not sure as to why this is failing. It has always worked in the past, but tonight it does not seem to want to cooperate.

**Comment by atom0s** [comment] 2015-12-11 05:48
I just reverted back to the older version of this script via:
npm install -g npm-windows-upgrade@0.4.4

Following that I was able to install the latest version of npm without issue. So it appears there is an issue with the latest version of this script.

**Comment by felixrieseberg** [comment] 2015-12-11 06:51
Thanks for reporting - I'll revert to that version right away and try to figure out what happened.

**Comment by felixrieseberg** [comment] 2015-12-11 16:57
@atom0s: Could you do me a giant favor and try version 0.5.3? I'm trying to zero in on the commit that broke things for you...

**Comment by atom0s** [comment] 2015-12-11 20:06
@felixrieseberg 0.5.3 seems to work fine as well. Upgraded to npm 3.5.3 without any issue.

**Comment by felixrieseberg** [comment] 2015-12-11 20:11
*Interesting*. Thank you so much, that'll help me investigate.

**Comment by atom0s** [comment] 2015-12-11 20:14
Not a problem, thank you for a great script. :)

**Comment by felixrieseberg** [comment] 2015-12-24 10:03
I have a feeling that this was is/connected to https://github.com/npm/npm/blob/master/CHANGELOG.md#attention-windows-users. I'm closing this therefore, even if the issue isn't entirely resolved - if I read the docs correctly, you can either try installing it with `npm install -f -g npm` - or by uninstalling and reinstalling Node (v5).

**Closed by felixrieseberg** 2015-12-24 10:03 UTC
