### ISSUE TITLE
Error:  WARN ENOENT ENOENT: no such file or directory

### ISSUE THREAD

**Issue by X-Y** [felixrieseberg/npm-windows-upgrade#48] opened 2015-11-13 14:39 UTC
Hi, my system is windows 10. I followed the instructions, and this is what comes out:

C:\WINDOWS\system32> npm-windows-upgrade
npm-windows-upgrade 0.5.1
? This tool will upgrade npm. Do you want to continue? (Y/n) Y
? This tool will upgrade npm. Do you want to continue? Yes
? Which version do you want to install? 3.3.12
Upgrading... \Error:  npm
Error:   WARN ENOENT ENOENT: no such file or directory, open 'C:\Program Files\nodejs\package.json'

Error:  npm
Error:   WARN EPACKAGEJSON nodejs No description

Error:  npm
Error:   WARN EPACKAGEJSON nodejs No repository field.

Error:  npm WARN EPACKAGEJSON nodejs No README data

Error:  npm
Error:   WARN EPACKAGEJSON nodejs No license field.

Upgrading... |

Any idea why it's asking for the package.json? There's no such file in the location it's looking for.

**Comment by kirillbunin** [comment] 2015-11-15 14:20
I've had this issue.
Adding `%appdata%\npm;%ProgramFiles%\nodejs;` to **system** PATH (bottom half of the system window) did the trick for me.

**Comment by felixrieseberg** [comment] 2015-11-16 08:17
Weird, I'm kind of confused. It should have been on the path to begin with, right? I'll see if there's a fix for this, but if somebody has ideas about the root cause, I'd love to hear them.

**Comment by X-Y** [comment] 2015-11-16 10:55
Thanks! This solves the problem. %ProgramFiles%\nodejs is cool, but %appdata%\npm is not in system PATH(it may be in user PATH by default, or I added it there).

**Comment by jwuliger** [comment] 2015-11-19 16:06
Hey guys! I am also having an issue that is related. I am able to upgrade my global NPM without a problem. When I try to upgrade NPM in my default node directory I get **PermissionDenied**. I am on windows 10 Ent and I am the sole admin.

```
Upgrading... /Error:  Test-Path : Access is denied
At C:\Users\jwuliger\AppData\Roaming\npm\node_modules\npm-windows-upgrade\powershell\upgrade-npm.ps1:95 char:6

Error:  + if ((Test-Path $AssumedNpmPath) -ne $True)
+      ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Program File...ode_modules\npm:String) [Test-Path], UnauthorizedAccessException
    + FullyQualifiedErrorId : ItemExistsUnauthorizedAccessError,Microsoft.PowerShell.Commands.TestPathCommand
```
Thanks for any help!

**Comment by felixrieseberg** [comment] 2015-11-19 16:30
Thanks for reporting! Obviously, that's weird. I just pushed 0.5.2, which should ignore permission errors when testing a path and silently continue - the fact that you don't have access to your own files is still troublesome though. Would you mind running `npm install -g npm-windows-upgrade` and telling me if it works now?

**Comment by jwuliger** [comment] 2015-11-19 16:56
Awesome! Thanks. I installed 0.5.2. New error message:

```
C:\Windows\system32>npm-windows-upgrade --npm-path:"C:\Program Files (x86)\nodejs"
npm-windows-upgrade 0.5.2
? This tool will upgrade npm. Do you want to continue? (Y/n) y
? This tool will upgrade npm. Do you want to continue? Yes
? Which version do you want to install? 3.4.1
Upgrading... /Error:  module.js:339
    throw err;
    ^

Error: Cannot find module 'C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

I also find it strange that I do not have permissions. I went to the directory and it seems to be an issues with the node_modules directory. I am not 100% though. Again thanks for your help!

**Comment by jshepler** [comment] 2015-11-19 20:48
Same error as OP. Fresh install of node and npm-windows-upgrade 0.5.2. System path did not have %appdata%\npm, but User path did. Added to system path before nodejs (as specified at https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows ) and it worked.

**Comment by jwuliger** [comment] 2015-11-19 23:48
@jshepler Thanks for that link. I got everything sorted. Thanks for the help!

**Comment by felixrieseberg** [comment] 2015-11-23 11:20
Hey everyone, I just pushed a small update to `npm-windows-upgrade` - we'll now make sure that npm is on the system path (and in front of any nodejs path variables). I'm closing this for now, but thank you so much for reporting!

**Closed by felixrieseberg** 2015-11-23 11:20 UTC

**Comment by benmccallum** [comment] 2016-01-02 09:17
I'm getting the same issue. I installed nodejs with Chocolatey and I believe that's the issue for me. 

I don't have a 'C:\Program Files\nodejs\package.json', but from the comments it seems that is normal.

I don't have %appdata%\npm in my system path, only in my user path. So i guess that's a limitation of Chocolatey installer for nodejs?
